In [1]:
# 라이브러리
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import scipy as spst

# 한글폰트 지정(맑은고딕)
plt.rcParams['font.family'] = 'Malgun Gothic'
plt.rcParams['axes.unicode_minus'] = False

# 고해상도
%config InlineBackend.figure_format = 'retina'

- 오픈 API를 사용해 데이터를 가져옵니다

In [2]:
# 라이브러리 불러오기
import urllib.request 
import json

- 한국도로공사 고속도로 공공데이터

In [28]:
# 인증키와 주소

# key = '5603003178'
# iYear = 2022
# numOfRows = 23
# pageNo = 1
#---------------------------------------------------------------------------------
result = []
pageNo = 1
# 반복해서 가져와 연결하기
while True:

    url = f'http://data.ex.co.kr/openapi/specialAnal/intercityLeadTime?key=5603003178&type=json&iYear=2022&iStUnitCode=101&iEdUnitCode=140&numOfRows=23&pageNo={pageNo}'

    # 데이터 가져와 인코딩
    response = urllib.request.urlopen(url) 
    json_str = response.read().decode('utf-8')
    json_object = json.loads(json_str)
    
    result += json_object['intercityLeadTimeLists']
    
    
    if pageNo ==  11:  # 11페이지가 마지막
        break
    pageNo += 1    
    
# 확인
dochak = pd.json_normalize(result)
dochak.head()

KeyboardInterrupt:

In [ ]:
dochak

In [ ]:
dochak['sphlDfttNm'].value_counts()

In [ ]:
dochak.shape

In [ ]:
result = []
pageNo = 1
# 반복해서 가져와 연결하기
while True:

    url = f'http://data.ex.co.kr/openapi/specialAnal/intercityLeadTime?key=5603003178&type=json&iYear=2021&iStUnitCode=101&iEdUnitCode=140&numOfRows=23&pageNo={pageNo}'

    # 데이터 가져와 인코딩
    response = urllib.request.urlopen(url) 
    json_str = response.read().decode('utf-8')
    json_object = json.loads(json_str)
    
    result += json_object['intercityLeadTimeLists']
    
    
    if pageNo ==  18:  # 11페이지가 마지막
        break
    pageNo += 1    
    
# 확인
dochak_2021 = pd.json_normalize(result)
dochak_2021.head()

In [ ]:
result = []
pageNo = 1
# 반복해서 가져와 연결하기
while True:

    url = f'http://data.ex.co.kr/openapi/specialAnal/intercityLeadTime?key=5603003178&type=json&iYear=2020&iStUnitCode=101&iEdUnitCode=140&numOfRows=23&pageNo={pageNo}'

    # 데이터 가져와 인코딩
    response = urllib.request.urlopen(url) 
    json_str = response.read().decode('utf-8')
    json_object = json.loads(json_str)
    
    result += json_object['intercityLeadTimeLists']
    
    
    if pageNo ==  19:  # 11페이지가 마지막
        break
    pageNo += 1    
    
# 확인
dochak_2020 = pd.json_normalize(result)
dochak_2020.head()

In [31]:
result = []
pageNo = 1
# 반복해서 가져와 연결하기
while True:

    url = f'http://data.ex.co.kr/openapi/specialAnal/intercityLeadTime?key=5603003178&type=json&iYear=2019&iStUnitCode=101&iEdUnitCode=140&numOfRows=23&pageNo={pageNo}'

    # 데이터 가져와 인코딩
    response = urllib.request.urlopen(url) 
    json_str = response.read().decode('utf-8')
    json_object = json.loads(json_str)
    
    result += json_object['intercityLeadTimeLists']
    
    
    if pageNo ==  17:  # 11페이지가 마지막
        break
    pageNo += 1    
    
# 확인
dochak_2019 = pd.json_normalize(result)
dochak_2019.head()

,stdHour,iYear,iStUnitCode,iEdUnitCode,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,stUnitCode,edUnitNm,edUnitCode,dirNm,dirCode,trtm,message,code
0,00,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,291.033000000000000000000000,None,None
1,01,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,253.341500000000000000000000,None,None
2,02,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,272.950000000000000000000000,None,None
3,03,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,254.358000000000000000000000,None,None
4,04,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,243.661000000000000000000000,None,None

In [46]:
dochak_2019.head()

,stdHour,iYear,iStUnitCode,iEdUnitCode,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,stUnitCode,edUnitNm,edUnitCode,dirNm,dirCode,trtm,message,code
0,00,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,291.033000000000000000000000,None,None
1,01,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,253.341500000000000000000000,None,None
2,02,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,272.950000000000000000000000,None,None
3,03,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,254.358000000000000000000000,None,None
4,04,None,None,None,2019,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,243.661000000000000000000000,None,None

In [51]:
tmp = dochak_2019.loc[(dochak_2019['sphlDfttNm'] == '추석'),:]
tmp[50:100]

,stdHour,iYear,iStUnitCode,iEdUnitCode,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,stUnitCode,edUnitNm,edUnitCode,dirNm,dirCode,trtm,message,code
307,02,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,355.966500000000000000000000,None,None
308,03,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,365.291500000000000000000000,None,None
309,04,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,476.171666666666666666666666,None,None
310,05,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,481.954000000000000000000000,None,None
311,06,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,496.029000000000000000000000,None,None
312,07,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,468.466500000000000000000000,None,None
313,08,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,478.327666666666666666666666,None,None
314,09,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,470.749500000000000000000000,None,None
315,10,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,475.974500000000000000000000,None,None
316,11,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,501.761000000000000000000000,None,None
317,12,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,471.191000000000000000000000,None,None
318,13,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,471.441500000000000000000000,None,None
319,14,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,498.516400000000000000000000,None,None
320,15,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,511.016500000000000000000000,None,None
321,16,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,496.154000000000000000000000,None,None
322,17,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,466.991000000000000000000000,None,None
323,18,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,483.638333333333333333333333,None,None
324,19,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,453.372000000000000000000000,None,None
325,20,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,390.000000000000000000000000,None,None
326,21,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,393.555333333333333333333333,None,None
327,22,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,382.116500000000000000000000,None,None
328,23,None,None,None,2019,추석,3,D-1,3,서울,101,부산,140,귀성방향,1,372.341000000000000000000000,None,None
329,00,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,285.675000000000000000000000,None,None
330,01,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,286.016500000000000000000000,None,None
331,02,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,284.908000000000000000000000,None,None
332,03,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,276.774500000000000000000000,None,None
333,04,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,293.400000000000000000000000,None,None
334,08,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,224.483000000000000000000000,None,None
335,09,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,240.133000000000000000000000,None,None
336,10,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,246.800000000000000000000000,None,None
337,11,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,228.666000000000000000000000,None,None
338,12,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,240.866500000000000000000000,None,None
339,13,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,249.041000000000000000000000,None,None
340,14,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,256.475000000000000000000000,None,None
341,15,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,256.116000000000000000000000,None,None
342,16,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,262.616500000000000000000000,None,None
343,17,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,265.949500000000000000000000,None,None
344,18,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,263.171666666666666666666666,None,None
345,19,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,264.250000000000000000000000,None,None
346,20,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,263.133000000000000000000000,None,None
347,21,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,257.700000000000000000000000,None,None
348,22,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,261.833000000000000000000000,None,None
349,23,None,None,None,2019,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,265.341000000000000000000000,None,None
350,00,None,None,None,2019,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,267.433000000000000000000000,None,None
351,01,None,None,None,2019,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,242.499500000000000000000000,None,None
352,02,None,None,None,2019,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,260.483000000000000000000000,None,None
353,03,None,None,None,2019,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,257.983000000000000000000000,None,None
354,04,None,None,None,2019,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,254.300000000000000000000000,None,None
355,05,None,None,None,2019,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,265.233000000000000000000000,None,None
356,06,None,None,None,2019,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,276.291500000000000000000000,None,None

In [42]:
dochak_2019.shape

(374, 18)

In [9]:
result = []
pageNo = 1
# 반복해서 가져와 연결하기
while True:

    url = f'http://data.ex.co.kr/openapi/specialAnal/intercityLeadTime?key=5603003178&type=json&iYear=2018&iStUnitCode=101&iEdUnitCode=140&numOfRows=23&pageNo={pageNo}'

    # 데이터 가져와 인코딩
    response = urllib.request.urlopen(url) 
    json_str = response.read().decode('utf-8')
    json_object = json.loads(json_str)
    
    result += json_object['intercityLeadTimeLists']
    
    
    if pageNo ==  19:  # 11페이지가 마지막
        break
    pageNo += 1    
    
# 확인
dochak_2018 = pd.json_normalize(result)
dochak_2018.head()

,stdHour,iYear,iStUnitCode,iEdUnitCode,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,stUnitCode,edUnitNm,edUnitCode,dirNm,dirCode,trtm,message,code
0,00,None,None,None,2018,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,228.441000000000000000000000,None,None
1,01,None,None,None,2018,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,232.283000000000000000000000,None,None
2,02,None,None,None,2018,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,236.333000000000000000000000,None,None
3,03,None,None,None,2018,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,230.875000000000000000000000,None,None
4,04,None,None,None,2018,연말연시,1,D,4,서울,101,부산,140,귀성방향,1,235.774500000000000000000000,None,None

In [10]:
result = []
pageNo = 1
# 반복해서 가져와 연결하기
while True:

    url = f'http://data.ex.co.kr/openapi/specialAnal/intercityLeadTime?key=5603003178&type=json&iYear=2017&iStUnitCode=101&iEdUnitCode=140&numOfRows=23&pageNo={pageNo}'

    # 데이터 가져와 인코딩
    response = urllib.request.urlopen(url) 
    json_str = response.read().decode('utf-8')
    json_object = json.loads(json_str)
    
    result += json_object['intercityLeadTimeLists']
    
    
    if pageNo ==  8:  # 11페이지가 마지막
        break
    pageNo += 1    
    
# 확인
dochak_2017 = pd.json_normalize(result)
dochak_2017.head()

,stdHour,iYear,iStUnitCode,iEdUnitCode,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,stUnitCode,edUnitNm,edUnitCode,dirNm,dirCode,trtm,message,code
0,00,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,274.466000000000000000000000,None,None
1,01,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,260.141000000000000000000000,None,None
2,02,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,269.225000000000000000000000,None,None
3,03,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,263.721666666666666666666666,None,None
4,04,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,264.088666666666666666666666,None,None

In [12]:
print(dochak_2017.shape)
print(dochak_2018.shape)
print(dochak_2019.shape)
print(dochak_2020.shape)
print(dochak_2021.shape)

(168, 18)
(423, 18)
(374, 18)
(418, 18)
(414, 18)

In [15]:
data = pd.concat([dochak_2017, dochak_2018],axis=0,join='inner')
data = pd.concat([data, dochak_2019],axis=0,join='inner')
data = pd.concat([data, dochak_2020],axis=0,join='inner')
data = pd.concat([data, dochak_2021],axis=0,join='inner')
data = pd.concat([data, dochak],axis=0,join='inner')
# print(data.head(2))
# print(data.tail(2))

In [17]:
data.columns

Index(['stdHour', 'iYear', 'iStUnitCode', 'iEdUnitCode', 'stdYear',
       'sphlDfttNm', 'sphlDfttCode', 'sphlDfttScopTypeNm',
       'sphlDfttScopTypeCode', 'stUnitNm', 'stUnitCode', 'edUnitNm',
       'edUnitCode', 'dirNm', 'dirCode', 'trtm', 'message', 'code'],
      dtype='object')

In [ ]:
data['dirNm'].value_counts()

In [20]:
del_cols = ['iYear','iStUnitCode','iEdUnitCode','stUnitCode','edUnitCode','dirNm','dirCode','message','code']

data.drop(del_cols, axis =1 ,inplace=True)
data.head()

,stdHour,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,edUnitNm,trtm
0,00,2017,추석,3,D-3,1,서울,부산,274.466000000000000000000000
1,01,2017,추석,3,D-3,1,서울,부산,260.141000000000000000000000
2,02,2017,추석,3,D-3,1,서울,부산,269.225000000000000000000000
3,03,2017,추석,3,D-3,1,서울,부산,263.721666666666666666666666
4,04,2017,추석,3,D-3,1,서울,부산,264.088666666666666666666666

In [22]:
data.columns = ['시간', '연도', '연휴', 'sphlDfttCode',
       'sphlDfttScopTypeNm', 'sphlDfttScopTypeCode', '출발지', '도착지',
       '소요시간(분)']

data.head(2)

,시간,연도,연휴,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,출발지,도착지,소요시간(분)
0,00,2017,추석,3,D-3,1,서울,부산,274.466000000000000000000000
1,01,2017,추석,3,D-3,1,서울,부산,260.141000000000000000000000

In [31]:
data.reset_index(drop= True, inplace=True)
data.tail()

,시간,연도,연휴,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,출발지,도착지,소요시간(분)
2045,19,2022,설날,2,D+3,7,서울,부산,265.266500000000000000000000
2046,20,2022,설날,2,D+3,7,서울,부산,271.666000000000000000000000
2047,21,2022,설날,2,D+3,7,서울,부산,270.850000000000000000000000
2048,22,2022,설날,2,D+3,7,서울,부산,270.016000000000000000000000
2049,23,2022,설날,2,D+3,7,서울,부산,262.616000000000000000000000

In [15]:
data.to_csv('df_traffic.csv', index=False)

In [16]:
data= pd.read_csv('df_traffic.csv')
data.tail()

,시간,연도,연휴,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,출발지,도착지,소요시간(분)
2045,19,2022,설날,2,D+3,7,서울,부산,265.2665
2046,20,2022,설날,2,D+3,7,서울,부산,271.6660
2047,21,2022,설날,2,D+3,7,서울,부산,270.8500
2048,22,2022,설날,2,D+3,7,서울,부산,270.0160
2049,23,2022,설날,2,D+3,7,서울,부산,262.6160

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2050 entries, 0 to 2049
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   시간                    2050 non-null   int64
 1   연도                    2050 non-null   int64
 2   연휴                    2050 non-null   object
 3   sphlDfttCode          2050 non-null   int64
 4   sphlDfttScopTypeNm    2050 non-null   object
 5   sphlDfttScopTypeCode  2050 non-null   int64
 6   출발지                   2050 non-null   object
 7   도착지                   2050 non-null   object
 8   소요시간(분)               2036 non-null   float64
dtypes: float64(1), int64(4), object(4)
memory usage: 144.3+ KB

- 결측치 확인 및 제거 보완

In [18]:
tmp_nan = data['소요시간(분)'][data['소요시간(분)'].isna()]
# subway_dfd['도로명주소'][subway_df['도로명주소'].isnull()]
NaN_list = list(tmp_nan.index)

In [19]:
for i in NaN_list:
    print(data['연휴'][i:i+1])

195    연말연시
Name: 연휴, dtype: object
572    추석
Name: 연휴, dtype: object
663    연말연시
Name: 연휴, dtype: object
992    연말연시
Name: 연휴, dtype: object
1200    설날
Name: 연휴, dtype: object
1452    연말연시
Name: 연휴, dtype: object
1473    설날
Name: 연휴, dtype: object
1474    설날
Name: 연휴, dtype: object
1592    설날
Name: 연휴, dtype: object
1756    추석
Name: 연휴, dtype: object
1873    연말연시
Name: 연휴, dtype: object
1988    설날
Name: 연휴, dtype: object
1989    설날
Name: 연휴, dtype: object
2026    설날
Name: 연휴, dtype: object

In [20]:
data_chu = data.loc[data['연휴']=='추석',:]
data_chu.drop(columns= 'sphlDfttCode', axis = 1, inplace = True)	
data_chu.reset_index(drop=True, inplace=True)

data_chu.columns = ['시간', '연도', '연휴', '추석기준',
       '연휴길이', '출발지', '도착지', '소요시간(분)']
data_chu.tail()

C:\Users\User\AppData\Local\Temp\ipykernel_12380\2289402035.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  data_chu.drop(columns= 'sphlDfttCode', axis = 1, inplace = True)

     시간    연도  연휴 추석기준  연휴길이 출발지 도착지  소요시간(분)
767  18  2021  추석  D+3     7  서울  부산  277.775
768  19  2021  추석  D+3     7  서울  부산  286.816
769  20  2021  추석  D+3     7  서울  부산  301.116
770  21  2021  추석  D+3     7  서울  부산  315.433
771  22  2021  추석  D+3     7  서울  부산  329.733

In [23]:
data_chu.head()

   시간    연도  연휴 추석기준  연휴길이 출발지 도착지     소요시간(분)
0   0  2017  추석  D-3     1  서울  부산  274.466000
1   1  2017  추석  D-3     1  서울  부산  260.141000
2   2  2017  추석  D-3     1  서울  부산  269.225000
3   3  2017  추석  D-3     1  서울  부산  263.721667
4   4  2017  추석  D-3     1  서울  부산  264.088667

In [24]:
data_chu.to_csv('df_data_chu.csv', index=False)

In [59]:
result = []
# pageNo = 1
# 반복해서 가져와 연결하기
# year = 2017
k = 0

for year in range(2017,2023):
    pageNo = 1 
    while True:

        url = f'http://data.ex.co.kr/openapi/specialAnal/intercityLeadTime?key=5603003178&type=json&iYear={year}&iStUnitCode=101&iEdUnitCode=140&numOfRows=100&pageNo={pageNo}'

        # 데이터 가져와 인코딩
        response = urllib.request.urlopen(url) 
        json_str = response.read().decode('utf-8')
        json_object = json.loads(json_str)

        result += json_object['intercityLeadTimeLists']


        if pageNo > json_object['pageSize'] :  
            break
        pageNo += 1    

# 확인
dochak = pd.json_normalize(result)
dochak.shape

(1797, 18)

In [55]:
dochak.head()

,stdHour,iYear,iStUnitCode,iEdUnitCode,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,stUnitCode,edUnitNm,edUnitCode,dirNm,dirCode,trtm,message,code
0,00,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,274.466000000000000000000000,None,None
1,01,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,260.141000000000000000000000,None,None
2,02,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,269.225000000000000000000000,None,None
3,03,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,263.721666666666666666666666,None,None
4,04,None,None,None,2017,추석,3,D-3,1,서울,101,부산,140,귀성방향,1,264.088666666666666666666666,None,None

In [58]:
dochak.tail(60)

,stdHour,iYear,iStUnitCode,iEdUnitCode,stdYear,sphlDfttNm,sphlDfttCode,sphlDfttScopTypeNm,sphlDfttScopTypeCode,stUnitNm,stUnitCode,edUnitNm,edUnitCode,dirNm,dirCode,trtm,message,code
1737,06,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,237.783000000000000000000000,None,None
1738,07,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,268.016000000000000000000000,None,None
1739,08,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,242.083000000000000000000000,None,None
1740,09,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,248.358000000000000000000000,None,None
1741,10,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,247.999500000000000000000000,None,None
1742,11,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,259.866000000000000000000000,None,None
1743,12,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,262.166333333333333333333333,None,None
1744,13,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,266.358000000000000000000000,None,None
1745,14,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,270.541000000000000000000000,None,None
1746,15,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,273.558000000000000000000000,None,None
1747,16,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,258.749666666666666666666666,None,None
1748,17,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,276.816000000000000000000000,None,None
1749,18,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,269.541500000000000000000000,None,None
1750,19,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,267.333000000000000000000000,None,None
1751,20,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,250.208000000000000000000000,None,None
1752,21,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,277.483000000000000000000000,None,None
1753,22,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,270.683000000000000000000000,None,None
1754,23,None,None,None,2021,추석,3,D+1,5,서울,101,부산,140,귀성방향,1,263.866000000000000000000000,None,None
1755,00,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,225.483000000000000000000000,None,None
1756,05,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,None,None,None
1757,06,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,227.116000000000000000000000,None,None
1758,07,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,236.983000000000000000000000,None,None
1759,08,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,218.400000000000000000000000,None,None
1760,09,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,215.458000000000000000000000,None,None
1761,10,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,225.949500000000000000000000,None,None
1762,11,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,236.324500000000000000000000,None,None
1763,12,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,240.983000000000000000000000,None,None
1764,13,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,243.108000000000000000000000,None,None
1765,14,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,249.094000000000000000000000,None,None
1766,15,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,259.149666666666666666666666,None,None
1767,16,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,263.166500000000000000000000,None,None
1768,17,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,243.616000000000000000000000,None,None
1769,18,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,254.216000000000000000000000,None,None
1770,19,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,256.516000000000000000000000,None,None
1771,20,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,258.800000000000000000000000,None,None
1772,21,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,265.433000000000000000000000,None,None
1773,22,None,None,None,2021,추석,3,D+2,6,서울,101,부산,140,귀성방향,1,300.650000000000000000000000,None,None
1774,00,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,233.333000000000000000000000,None,None
1775,01,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,293.716000000000000000000000,None,None
1776,02,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,281.900000000000000000000000,None,None
1777,03,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,270.100000000000000000000000,None,None
1778,04,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,258.283000000000000000000000,None,None
1779,05,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,246.466000000000000000000000,None,None
1780,06,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,253.183000000000000000000000,None,None
1781,07,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,266.566000000000000000000000,None,None
1782,08,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,269.316000000000000000000000,None,None
1783,09,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,266.549500000000000000000000,None,None
1784,10,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,264.216500000000000000000000,None,None
1785,11,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,269.641000000000000000000000,None,None
1786,12,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,271.266000000000000000000000,None,None
1787,13,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,266.341500000000000000000000,None,None
1788,14,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,263.083000000000000000000000,None,None
1789,15,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,272.441000000000000000000000,None,None
1790,16,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,271.983000000000000000000000,None,None
1791,17,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,279.772000000000000000000000,None,None
1792,18,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,277.775000000000000000000000,None,None
1793,19,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,286.816000000000000000000000,None,None
1794,20,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,301.116000000000000000000000,None,None
1795,21,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,315.433000000000000000000000,None,None
1796,22,None,None,None,2021,추석,3,D+3,7,서울,101,부산,140,귀성방향,1,329.733000000000000000000000,None,None